name: Release Workflow

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      artifacts:
        required: true
        type: string
      # you'll need to add these into your consuming job to expose them
      tag:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  setup-and-build:
    uses: ./.github/workflows/setup-and-build.yml
    with:
      platform: ${{inputs.platform}}

  release:
    runs-on: ${{inputs.platform}}
    needs: setup-and-build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Restore Rust Dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{inputs.platform}}-${{github.sha}}

      - name: Run Cargo Build
        run:
          cargo build --release

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{inputs.artifacts}}
          name: ${{inputs.name}}
          # can eventually pull commit messages to include in the body
          tag: ${{inputs.tag}}
          # will remove this once the tool is out of the alpha/pre-release stage
          prerelease: true
          # do we need this? Might want to review what's produced
          draft: true